const json = {
    accesses: [],
    agendajobs: [],
    apitools: [],
    assertions: [],
    audiocodessettings: [],
    audits: [
        'documentAfterAccess.thumbnail',
        'documentAfterAccess.chatBotDesign.botImage',
        'documentAfterAccess.icon',
        'documentAfterAccess.logo',
        'documentAfterAccess.qrCode.url',
        'documentAfterAccess.carousels.image',
        'documentAfterAccess.card.image',
        'documentAfterAccess.list.listItems.image',
        'documentAfterAccess.buttonWithImage.button.image',
        'documentAfterAccess.chatBotDesign.startIconOptions.image',
        'documentAfterAccess.card.url'
    ],
    bdks: [],
    bots: ['chatBotDesign.botImage',
        'chatBotDesign.startIconOptions.image'],
    bots_old: [],
    bottriggerpoints: [],
    botusers: [],
    broadcastexecutors: [],
    campaigns: ['audioCodes.fileUrl'],
    confusionmatrixes: [],
    conversationdetailshistories: [],
    conversationhistories: [],
    conversations: ['conversationData'],
    departments: [],
    dialogflowauths: [],
    dialogflowentities: [],
    dialogflowintents: [],
    dialogflowsytementities: [],
    dialogflowtokens: [],
    dialogflowtrainings: [],
    entities: [],
    fallbacks: [],
    fallbacktrainings: [],
    fis: [],
    flowblocksteps: ['icon'],
    flowfolders: [],
    flowhistories: [],
    flows: ['thumbnail'],
    flowsteps: [
        'media.link',
        'card.image',
        'carousels.image',
        'list.listItems.image',
        'review.reviewChoices.image',
        'buttonWithImage.button.image',
        'checklist.checklistItems.image',
        'FI.value',
        'card.url',
        'carousels.buttons.value',
        'card.buttons.value'
    ],
    flowversions: ['difference.lhs.link',
        'difference.lhs.blockSteps.icon',
        'difference.lhs.blockSteps.flowSteps.card.image',
        'difference.lhs.thumbnail',
        'difference.rhs',
        'difference.lhs',
        'difference.item.lhs.card.image',
        'difference.item.rhs.card.image',
        'difference.rhs.image',
        'difference.lhs.blockSteps.flowSteps.carousels.image',
        'difference.item.rhs.image',
        'difference.lhs.blockSteps.flowSteps.list.listItems.image',
        'difference.item.rhs.flowSteps.media.link',
        'difference.item.lhs.media.link',
        'difference.item.rhs.media.link',
        'difference.item.lhs.flowSteps.media.link',
        'difference.item.lhs.flowSteps.carousels.image',
        'difference.lhs.blockSteps.flowSteps.media.link',
        'difference.lhs.blockSteps.flowSteps.buttonWithImage.button.image',
        'difference.item.lhs.flowSteps.list.listItems.image',
        'difference.item.lhs.flowSteps.card.image',
        'difference.item.lhs.flowSteps.checklist.checklistItems.image',
        'difference.lhs.blockSteps.flowSteps.carousels.buttons.value',
        'difference.lhs.blockSteps.flowSteps.card.url',
        'difference.lhs.blockSteps.flowSteps.card.buttons.value',
        'difference.lhs.blockSteps.flowSteps.review.reviewChoices.image',
        'difference.item.lhs.flowSteps.buttonWithImage.button.image',
        'difference.item.lhs.flowSteps.review.reviewChoices.image',
        'difference.item.lhs.flowSteps.card.url',
        'difference.item.lhs.flowSteps.FI.value',
        'difference.item.lhs.image',
        'difference.lhs.blockSteps.flowSteps.FI.value',
        'difference.lhs.blockSteps.flowSteps.checklist.checklistItems.image',
        'difference.rhs.link',
        'difference.lhs.image',
        'difference.item.lhs.icon'
    ],
    forms: [],
    growthtools: ['qrCode.url'],
    'handoff-designs': [],
    'handoff-messages': [],
    handoffs: [],
    handoffv1: [],
    ibmdiscoverydocuments: ['filePath'],
    icons: [],
    instagramsettings: [],
    intentfolderolds: [],
    intentfolders: [],
    intentmappings: [],
    intents: [],
    keywords: [],
    knowledgebases: [],
    mediauploads: [],
    messages: ['attachment.contentUrl'],
    msteamstokens: [],
    multinlps: [],
    navigators: [],
    nlphistories: [],
    nlphistoryolds: [],
    nlpolds: [],
    nlps: [],
    nlptraininghistories: [],
    notes: [],
    operations: [],
    organizations: ['logo'],
    previewlinks: [],
    profiles: [],
    ruleexecutors: [],
    rules: [],
    saasagendajobs: [],
    sankygraphs: [],
    schedulemessageconfigs: [],
    services: [],
    servicetokens: [],
    slacksettings: [],
    snapshots: [],
    snapshotsteps: [],
    systementities: [],
    taganalytics: [],
    tags: [],
    templatemessages: [],
    transcripts: [
        'card.image_url.url',
        'video.url',
        'audio.url',
        'image.url',
        'carousel.image_url',
        'pdf.url',
        'list.listItem.image',
        'review.reviewChoices.image',
        'buttonWithImage.button.image',
        'checklist.checklistItems.image',
        'doc.url',
        'ppt.url',
        'xls.url',
        'attachment.contentUrl',
        'interactive.header.video.link',
        'carousel.maskedData.image_url',
        'checklist.maskedData.checklistItems.image',
        'card.maskedData.image_url.url',
        'review.maskedData.reviewChoices.image',
        'list.maskedData.listItem.image',
        'buttonWithImage.maskedData.button.image',
        'video.maskedData.url',
        'translatedObj.image_url',
        'translatedObj.image_url.url',
        'translatedObj.reviewChoices.image',
        'translatedObj.listItem.image',
        'translatedObj.checklistItems.image',
        'translatedObj.button.image',
        'image.maskedData.url',
        'doc.maskedData.url',
        'xls.maskedData.url',
        'translatedObj.maskedData.image_url',
        'translatedObj.maskedData.image_url.url',
        'translatedObj.maskedData.listItem.image',
        'translatedObj.maskedData.checklistItems.image',
        'translatedObj.maskedData.button.image',
        'audio.maskedData.url',
        'pdf.maskedData.url',
        'ppt.maskedData.url'
    ],
    universalauths: [],
    'unpublished-flowblocksteps': ['icon'],
    'unpublished-flows': ['thumbnail'],
    'unpublished-flowsteps': ['carousels.image',
        'media.link',
        'buttonWithImage.button.image',
        'review.reviewChoices.image',
        'list.listItems.image',
        'checklist.checklistItems.image',
        'card.image',
        'template.components.parameters.media.link',
        'interactiveButton.header.media.link',
        'carousels.buttons.value',
        'card.url',
        'card.buttons.value',
        'FI.value'],
    userfis: ['value'],
    users: ['notifications.data.profilePic', 'profileImage'],
    users_copy: [],
    voximplants: [],
    whatsappprofilesettings: [],
    whatsapptemplatemessages: [],
    whatsappwidgets: ['content.chatHeader.picture.url'],
    widgetconsentscreens: [],
}